name: Full CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build app
        run: echo "Building..."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: echo "Testing..."

  deploy-dev:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to dev
        run: echo "Deploying to development..."

  deploy-qa:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Deploy to QA
        run: echo "Deploying to QA..."
